#!name=World Peace
#!desc=Yet Another Redirect Module

[Rule]
DOMAIN-SET,https://dbl.oisd.nl/nsfw/, REJECT
DOMAIN-SUFFIX,fast.com,REJECT
DOMAIN-SUFFIX,ooklaserver.net,REJECT
DOMAIN-SUFFIX,speed.cloudflare.com,REJECT
DOMAIN-KEYWORD,speedtest,REJECT
DOMAIN-KEYWORD,speed,REJECT
USER-AGENT,SpeedTest*,REJECT
DOMAIN-KEYWORD,falundafa,REJECT
DOMAIN-KEYWORD,dongtaiwang,REJECT
DOMAIN-KEYWORD,minghui,REJECT
DOMAIN-KEYWORD,wujieliulan,REJECT
DOMAIN-KEYWORD,zhengjian,REJECT
DOMAIN-KEYWORD,dafahao,REJECT
DOMAIN-KEYWORD,epochtimes,REJECT
DOMAIN-KEYWORD,ntdtv,REJECT
DOMAIN-KEYWORD,voachinese,REJECT
DOMAIN-KEYWORD,appledaily,REJECT
DOMAIN-KEYWORD,nextdigital,REJECT
DOMAIN-KEYWORD,dalailama,REJECT
DOMAIN-KEYWORD,nytimes,REJECT
DOMAIN-KEYWORD,bloomberg,REJECT
DOMAIN-KEYWORD,independent,REJECT
DOMAIN-KEYWORD,freetibet,REJECT
DOMAIN-KEYWORD,citizenpowerfor,REJECT
DOMAIN-KEYWORD,chinadigitaltimes,REJECT
DOMAIN-SUFFIX,rfa.org,REJECT
DOMAIN-SUFFIX,theinitium.com,REJECT
DOMAIN-SUFFIX,tibet.net,REJECT
DOMAIN-SUFFIX,jw.org,REJECT
DOMAIN-SUFFIX,bannedbook.org,REJECT
DOMAIN-SUFFIX,org.osu.edu,REJECT
DOMAIN-SUFFIX,dw.com,REJECT
DOMAIN-SUFFIX,storm.mg,REJECT
DOMAIN-SUFFIX,yam.com,REJECT
DOMAIN-SUFFIX,ltn.com.tw,REJECT
DOMAIN-SUFFIX,mpweekly.com,REJECT
DOMAIN-SUFFIX,cup.com.hk,REJECT
DOMAIN,hm.baidu.com,REJECT
DOMAIN-KEYWORD,php?ad,REJECT
DOMAIN-SUFFIX,handanxinkai.com,REJECT
DOMAIN-SUFFIX,jianxinshanghai.com,REJECT
DOMAIN-SUFFIX,gtv.org,REJECT
